[package]
name = "rte-france"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
chrono = "0.4.38"
oauth2 = "4.4.2"
polars = { version = "0.43.1", features = ["timezones"] }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = "1.0.213"
serde_json = "1.0.132"
